test

diff --git a/.github/workflows/slack_test.yml b/.github/workflows/slack_test.yml
--- a/.github/workflows/slack_test.yml
+++ b/.github/workflows/slack_test.yml
@@ -7,55 +7,20 @@ on:
 jobs:
     build:
         runs-on: ubuntu-22.04
-        steps:
-            - name: Set Variables
-              run: echo "SHORT_GITHUB_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV
 
-            - name: Send custom JSON data to Slack workflow
-              id: slack
-              uses: slackapi/slack-github-action@v1.24.0
+        steps:
+            - name: Test Failure
+              run: exit 1
+
+            - name: If Actions Failure
+              run: echo "ACTIONS_STATUS=Failure" >> $GITHUB_ENV
+
+            - name: If Actions Success
+              run: echo "ACTIONS_STATUS=Success" >> $GITHUB_ENV
+
+            - name: Send Slack Message
+              if: ${{always()}}
+              uses: ./github/slack/slack_notify
               with:
-                  payload: |
-                      {
-                        "text": "${{github.repository}} actions result: ${{job.status}}",
-                        "blocks": [
-                          {
-                            "type": "header",
-                            "text": {
-                              "type": "plain_text",
-                              "text": "Actions Result : ${{job.status}}"
-                            }
-                          }
-                        ],
-                        "attachments": [
-                          {
-                            "color": "#36a64f",
-                            "blocks": [
-                              {
-                                "type": "section",
-                                "fields": [
-                                  {
-                                    "type": "mrkdwn",
-                                    "text": "*Repository:*\n${{github.repository}}"
-                                  },
-                                  {
-                                    "type": "mrkdwn",
-                                    "text": "*Author:*\n${{github.actor}}"
-                                  },
-                                  {
-                                    "type": "mrkdwn",
-                                    "text": "*Commit:*\n<${{github.event.head_commit.url}} | ${{env.SHORT_GITHUB_SHA}}>"
-                                  },
-                                  {
-                                    "type": "mrkdwn",
-                                    "text": "*Commit Message:*\n${{github.event.head_commit.message}}"
-                                  }
-                                ]
-                              }
-                            ]
-                          }
-                        ]
-                      }
-              env:
-                  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
-                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+                  status: ${{env.ACTIONS_STATUS}}
+                  slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
